### ISSUE TITLE
Allow to handle "task id variables" other than location and outcome variable

### ISSUE THREAD

**Issue by elray1** [reichlab/predtimechart#14]
Currently, the predtimechart component includes two drop-down menus at the top left for selecting the outcome variable and the "unit" (which in practice so far is a location). It might be nice to support other options here.

![image](https://user-images.githubusercontent.com/5132208/203619426-757f5a23-d051-4a70-b07e-db6527e85541.png)

Here are proposals for modifications to predtimechart that would achieve this:

- Proposal for _fetchData signature: `_fetchData(isForecast, originDate, targetKey, taskIds)`
    - Inputs
        - isForecast: boolean: retrieve forecast or truth data?
        - originDate: a reference date or "time zero" date for forecasts
        - targetKey: some kind of specification of the target or outcome variable
        - taskIds: an object with keys naming model task ids and their values.
            - Examples of taskIds:
                - Ex.1: US COVID-19 Forecast Hub
```
{
    location: “US”,  # unitAbbrev
}
```

                - Ex. 2: Scenario hub example described [here](https://github.com/reichlab/hub-infrastructure-experiments/tree/main/metadata-format-examples/complex-example)

```
{
    scenario_id: 1,
    location: “US”
}
```

- Proposal for modifications to options object:
    - Remove units and initial_unit
    - Add a new object called taskIds
    - Ex. 2:
```
{
    scenario_id: [
        {value: 1, text: “Scenario 1”},
        {value: 2, text: “Scenario 2”}
    ],
    location: [
        {value: “US”, text: “US”},
        {value: “01”, text: “Alabama”},
        …
    ]
}
```
- Drop-down menus, labels, and menu options are populated from options.taskIds
- When a selection is made, combined task id selections are assembled and passed as an argument to _fetchData

**Comment by matthewcornell** [comment]
**Q**: Would the scenario hub example cause a total of three dropdowns to show (outcome, scenario_id, and location)?

**Comment by elray1** [comment]
1. yes, a total of three dropdowns would show
2. maybe a new object as part of the options, perhaps called `initial_taskIds` (or should we be using snake case for everything -- `initial_task_ids`?), listing the `value` to use of the initial taskIds?.  In ex 2, we might have
```
{
    scenario_id: 1,
    location: “US”
}
```

**Comment by nickreich** [comment]
An overview of the concept of task-id variables can be found [here](https://hubdocs.readthedocs.io/en/latest/format/tasks.html#task-id-vars).

@matthewcornell I think one example of a multiple task-id hub is the latest round from the scenario hub. The definition of task-ids for this hub is [here](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/hub-config/tasks.json#L9). 

E.g. one file in this format is [here](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/UNCC-hierbin/2023-04-16-UNCC-hierbin.gz.parquet), with some rows of output looking like this:
```
     value origin_date location horizon   type type_id  scenario_id   target
1 116.7534  2023-04-16       01       1 sample       1 A-2023-04-16 inc hosp
2 137.7407  2023-04-16       01       2 sample       1 A-2023-04-16 inc hosp
3 129.1102  2023-04-16       01       3 sample       1 A-2023-04-16 inc hosp
4 128.5794  2023-04-16       01       4 sample       1 A-2023-04-16 inc hosp
5 121.4901  2023-04-16       01       5 sample       1 A-2023-04-16 inc hosp
6 140.3355  2023-04-16       01       6 sample       1 A-2023-04-16 inc hosp
```
