### ISSUE TITLE
ability to quickly select as of date

### ISSUE THREAD

**Issue by elray1** [reichlab/predtimechart#18]
rather than clicking the arrows a lot of times, it'd be nice if there was a way to quickly select the as of date.  I'm not sure if this is possible (may very well not be), but once issue #9 (vertical line or shaded region to indicate as of date) is completed, it would be convenient if you could drag that line or the boundary of the shaded region.  This may be out of reach working with plotly, though; in that case, I'm open to other options as well.

**Comment by nickreich** [comment]
I wonder if there could be a drop-down menu somewhere to "jump to" a specific date.

**Comment by elray1** [comment]
Or could we just detect a click on the plot, figure out the x axis coordinate, round to the nearest available as of date, and jump to it?
