### ISSUE TITLE
Add time series range slider for horizontal axis zooming

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/predtimechart#2]
Per @elray1 's comment on slack:
> Along the way, there will likely be misc. requests for updates to the viz component that could then be easily propagated to all sites that use it. For example, one that's high on my personal list is adding one of these [time series range slider](https://plotly.com/javascript/time-series/#time-series-with-rangeslider) things that lets you zoom in on a part of the plot's horizontal axis, and maintain that zoom in the app's state as you change other settings.

**Comment by matthewcornell** [comment]
Per @nickreich's [comment on slack](https://reichlab.slack.com/archives/C02DHSYQ1CP/p1667488771471149?thread_ts=1666647003.205399&cid=C02DHSYQ1CP):

> it looks to me as though the yaxis range selection is not preserved when clicking one of the blue buttons. The following sequence of figures shows an initial load of the page, a rectangular selection (not using the slider), and then a press of a blue arrow, which preserves the x-axis range selection but not the y-axis range selection.

![image](https://user-images.githubusercontent.com/1034007/199804945-84348950-7158-4a0d-9f86-50afa84a69e8.png)

![image(1)](https://user-images.githubusercontent.com/1034007/199804952-42205de6-81f8-4117-a494-81a1ffde8200.png)

![image(2)](https://user-images.githubusercontent.com/1034007/199804963-b7ca1ed2-e100-4083-bc32-d5b5448b1265.png)

**Comment by matthewcornell** [comment]
@elray1 adds:
> it's also not preserved when changing location or signal, but that is desirable.  so we would probably only want to preserve the vertical axis when navigating across dates within the same selections for the other things

**Comment by nickreich** [comment]
More from @elray1 :

> Roughly, we'll want to do similar logic to what you came up with for the x axis range preservation in around line 567 in the snippet you pasted above, but finding and preserving the y axis.
> Since whether or not we want to preserve the axis is dependent on whether we're updating the as of date or something else, probably makes sense to add a boolean argument to that function named something like preserveYLimits specifying whether or not the y axis should be preserved.
> In turn, seems like we might also then need to add a similar boolean to fetchDataUpdatePlot , which would only be true in the calls to that function from incrementAsOf and decrementAsOf, and false elsewhere?
