### ISSUE TITLE
tooltip not working at boundary of data and forecast

### ISSUE THREAD

**Issue by nickreich** [reichlab/predtimechart#21]
There is a useful tooltip that shows the date and count when you hover on/near a point on the chart. However, there is never a tooltip that is available at the last point in the time-series which also is the first point in the forecast. E.g. in the below screenshot, I can get a tooltip for Nov 26 (truth data as of 12/3) and Dec 10 (for the forecast) , but not one for Dec 3 (which should also show a truth data value as of 12/3).

![image](https://user-images.githubusercontent.com/1280767/206288410-f54a2e2c-4790-49c9-a1d9-b826f526c0f4.png)

**Comment by nickreich** [comment]
Noting that when there is separation between current and as-of truth the current truth value is available on the tooltip. Could this be an issue of overlapping lines? e.g. if the phantom forecast point that is needed to start the cone of uncertainty overlaps the actual data, maybe it masks the tooltip?

<img width="540" alt="image" src="https://user-images.githubusercontent.com/1280767/206455801-babf31fd-dcd7-4ed0-b738-6d2025d65ea0.png">

**Comment by matthewcornell** [comment]
I'm having trouble understanding the specific dates in question. All I see in the screenshot are the ones on the x axis (..., Nov 20, Dec 4, Dec 18, ...) but not the ones you mention (Nov 26, Dec 10, Dec 3). The x axis dates are Sundays.
