### ISSUE TITLE
calendar selection for last as of date doesn't work when using today in calendar widget when an earlier as of date is currently selected

### ISSUE THREAD

**Issue by elray1** [reichlab/predtimechart#25]
If I have used left arrow keys to select an early as of date, and then try to use the calendar to jump to the current time, I can't -- my best guess is that the calendar widget is not detecting a change from its current state, so "Apply" has no effect?  When I click on the widget, it opens up to the current date rather than the currently-selected as of date (See screenshot).  If I select a different date in the calendar widget, like May 22, it works.
![image](https://github.com/reichlab/predtimechart/assets/5132208/d767febb-376d-461a-ba22-0368c98e71ca)

**Comment by matthewcornell** [comment]
I've experienced something like this too, involving the blue today date. My workaround is to click a date just before today - it usually maps to the same as_of as today. To fix it I think we'd have to replace the widget with another component - I believe I determined that it's a bug that's not going to be fixed, but I can check that.
