### ISSUE TITLE
remove "opening triangle"

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/predtimechart#27]
From [this Slack thread](https://reichlab.slack.com/archives/C05UWT29KUM/p1701890034760189), @elray1 says:

> it would probably be easiest to turn off what Aaron has termed the “opening triangle” that is created by connecting the forecasts to the last observed data point.  This would involve removing `state.as_of_truth.date.slice(-1).concat(` from [these lines](https://github.com/reichlab/predtimechart/blob/dc5e78bfd3889cd010ff6a8672ffdec1e5ce8056/src/predtimechart.js#L1155-L1163). 

@nickreich's comment:
> the opening triangle issue .. is currently creating some very weird shapes for the models that have some “-1” horizons [see image below]

In the future we might add an `App.initialize()` option to control it.

![image](https://github.com/reichlab/predtimechart/assets/1034007/9127e7bc-78b1-4fc7-8773-68dc90f48f61)

**Comment by nickreich** [comment]
Unfortunately, I think the update didn't fix all of this. It removed the "opening triangle" but not the line connecting the end of the data with the start of the forecasts. See this screenshot. 
![image](https://github.com/reichlab/predtimechart/assets/1280767/87f41e43-dd33-4434-8457-0a55b2262360)
